### ISSUE TITLE
SamsungMusic Milk Radio

### ISSUE THREAD

**Issue by fionna115** [AyraHikari/SamsungMusicPort#10]
Hello,
Please I want to ask you about an issue that happened to me when I was trying to installed an app (Apk version) a korean app that is not available anymore, this one : https://twitter.com/143_913/status/1095521422242271234?s=20

I wanted to install this app to watch some old contents from a group called THE BOYZ 더보이즈

And I manage to find it : [https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.androidlist.co.kr/ite...g19rQvewlzYTQY](https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.androidlist.co.kr/item/android-apps/604517/com-samsung-radio/amp/&ved=2ahUKEwiA24K1l8X_AhVcVqQEHer-BDQQFnoECAcQAQ&usg=AOvVaw1p5XDb1mg19rQvewlzYTQY)

But when I click on it, it keep telling me " a server error has occurred please try again later" , no matter how much I try, and I don't know what to do?!!
This is the website : http://marketingweb.glb.samsungmilkradio.com
Is there anyway to have the contents that was on the website and the app??! Specifically the ones that THE BOYZ 더보이즈 had!!

**Comment by AyraHikari** [comment]
It required Korean region and Samsung device to use Samsung Milk Radio.
And has different package (com.samsung.radio) than Samsung Music itself.

**Comment by fionna115** [comment]
If I use a VPN that have South Korea adress, what do I need else??! As you said it has different package (com.samsung.radio) than Samsung Music itself.
Because I really really want to see those contents, I didn't find them anywhere and nobody unfortunately had recorded them 😕
