### ISSUE TITLE
Sometimes no sound after skipping song over Bluetooth

### ISSUE THREAD

**Issue by do-sch** [AyraHikari/SamsungMusicPort#12]
When playing music via Bluetooth, there is sometimes no sound if a song has been skipped. In the UI it then looks as if the new song is still playing. If I pause and play, the song then starts playing.

The smartphone is a Xiaomi Poco F3, the operating system is MIUI 14.0.11. The problem only affects Bluetooth. Everything plays normally via the normal speaker.

**Comment by do-sch** [comment]
It appears to be an MIUI bug. After switching to a custom ROM, the music player plays music normally via Bluetooth.

**Comment by Bubba7691** [comment]
Same here with Pixel 8 Pro. No matter if I use my JBL, Redme earbuds, or the car BT. Somerimes the next track remains silent, however, checking the phone, it is playing.
