### ISSUE TITLE
still has storage issue

### ISSUE THREAD

**Issue by kearmau5** [AyraHikari/SamsungMusicPort#2]
not showing anything
using redmi note 7 miui 12.5 A10
![Screenshot_2022-01-08-13-48-06-878_com sec android app music](https://user-images.githubusercontent.com/78478945/148646036-8fbc579d-e3de-49bc-99d2-01bb45321012.jpg)

**Comment by Tovape** [comment]
In the meantime use the SamsungMusic_16.2.19.5_b4_AyraHikari.apk | v1.0.0 | stable | 14478 | 2021-08-25 | 30.36 MB from [link](https://www.pling.com/p/1537956/) that one works for me

**Comment by kearmau5** [comment]
> In the meantime use the SamsungMusic_16.2.19.5_b4_AyraHikari.apk | v1.0.0 | stable | 14478 | 2021-08-25 | 30.36 MB from [link](https://www.pling.com/p/1537956/) that one works for me

That was long time ago bro now i use version 1.2.7 problem solved long time ago,forgot to close the issue
