### ISSUE TITLE
Constantly Crashing

### ISSUE THREAD

**Issue by Redvvt** [AyraHikari/SamsungMusicPort#9]
since i updated the app to the latest version(16.2.31.1), it is constantly crashing.  It doesn't even open.  I press it and it crashes.
I can't downgrade the app version neither

**Comment by AyraHikari** [comment]
Try redownloading again, because I've reuploaded the fixed one. If still persist, try capture logs with [Scoop](https://github.com/TacoTheDank/Scoop/releases) and paste in here.
